---
- name: "Install Node.js 13"
  shell: |
    # Install Node.js LTS version as our base Node.js version
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt-get install -y nodejs

    # Use n version manager to switch to Node.js v13.8.0
    sudo npm install -g n
    sudo n 13.8.0

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes

- name: "install docker."
  become: true
  apt:
    name: ["docker.io"]
    state: latest
    update_cache: yes

- name: Install docker-compose
  remote_user: zedan
  get_url: 
    url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x,o+x'

- copy:
    src: /home/circleci/project/util/docker-compose.yml
    dest: /home/zedan/

- name: Run PostgresQL DB
  become: True
  shell:
    cmd: "docker-compose -f docker-compose.yml up -d"
    chdir: .